# Usa la imagen base de Node.js para construir la aplicación
FROM node:14 AS build

# Establece el directorio de trabajo
WORKDIR /usr/src/app

# Copia los archivos de package.json y package-lock.json
COPY package*.json ./

# Instala las dependencias
RUN npm install

# Copia el resto de los archivos del proyecto
COPY . .

# Construye la aplicación
RUN npm run build --prod

# Usa una imagen más ligera para servir la aplicación
FROM nginx:alpine

# Copia los archivos de construcción a la carpeta de Nginx
COPY --from=build /usr/src/app/dist/proyect /usr/share/nginx/html

# Exponer el puerto que usa Nginx
EXPOSE 80

# Comando para iniciar Nginx
CMD ["nginx", "-g", "daemon off;"]
