# Usa la imagen base de Node.js
FROM node:23.1.0

# Establece el directorio de trabajo en la raíz del contenedor
WORKDIR /usr/src/app

# Copia los archivos de package.json y package-lock.json
COPY package*.json ./

# Instala las dependencias
RUN npm install

# Copia el resto de los archivos del proyecto al contenedor
COPY . .

# Expone el puerto que utiliza tu aplicación
EXPOSE 3010

# Comando para ejecutar la aplicación
CMD ["node", "servidor.js"]
